#!/bin/sh
exec 2>&1

exec podman run --rm \
  --name grafana \
  --user root \
  --publish 3000:3000 \
  --volume /home/admin/.local/share/grafana:/var/lib/grafana \
  --env-file /home/admin/.config/grafana/environment \
  grafana/grafana-oss:11.6.0
