#!/bin/sh
exec 2>&1

exec podman run --rm \
  --name mimir \
  --volume /home/admin/.config/mimir:/etc/mimir-config \
  --volume /home/admin/.local/share/mimir:/tmp/mimir \
  --publish 9009:9009 \
  docker.io/grafana/mimir:2.14.3 \
  -config.file=/etc/mimir-config/mimir.yaml
