#!/bin/sh
exec 2>&1

exec podman run --rm \
  --name loki \
  --user root \
  --volume /home/admin/.config/loki:/etc/loki \
  --volume /home/admin/.local/share/loki/data:/var/lib/loki \
  --volume /home/admin/.local/share/loki/tmp:/tmp \
  --publish 3100:3100 \
  --publish 9096:9096 \
  grafana/loki:3.4.2 \
  -config.file=/etc/loki/loki-config.yaml
