#!/bin/sh
exec 2>&1

exec podman run --rm \
  --name influxdb2 \
  --publish 8086:8086 \
  --volume /home/admin/.local/share/influxdb2:/var/lib/influxdb2 \
  --volume /home/admin/.config/influxdb2:/etc/influxdb2 \
  --env-file /home/admin/.config/influxdb2/environment \
  influxdb:2.7.11-alpine
