#!/bin/sh
exec 2>&1

exec podman run --rm \
--name podman-exporter \
--env CONTAINER_HOST=unix:///run/podman/podman.sock \
--volume /run/user/1000/podman/podman.sock:/run/podman/podman.sock \
--publish 9882:9882 \
--userns=keep-id:uid=65534 \
--security-opt label=disable \
quay.io/navidys/prometheus-podman-exporter \
/bin/podman_exporter --collector.enable-all
